# config.yaml
database:
  # 相対パスでも絶対パスでも指定可能にする
  path: "./db_exam/bbs.db" # relative
  track_modifications: false

server:
  port: 5000 # check docker-compose.yaml -> ports
  debug: true

# secret_key for app.secret_key
app_secret_key: "very_long_secret_key---ppNVKmGzRNG7hbnr-snbjGPihFfrXpD4LXkAyywNVUhbA3hpUu5YKPHsPDmxN4JdwHsgkHa2tYAe4iUy5Bcd"

